### ISSUE TITLE
Login Design

### ISSUE THREAD

**Issue by di48l069** [HaniAmmar/PlusFTP#1]
Hi there im busy creating a telnet client and like how you did your design of login may use a very similar design?

**Comment by NicoTravassos** [comment]
In terms of Account

**Comment by HaniAmmar** [comment]
Yes, you can :)
________________________________

**Comment by NicoTravassos** [comment]
Would you like any credits?

Wont be using any of your code just some of the wpf code how designed the login

**Comment by HaniAmmar** [comment]
It's all up to you.
________________________________

**Comment by NicoTravassos** [comment]
Thanks man

**Comment by NicoTravassos** [comment]
Sorry to bother but just see below image and see if thats okay if i use it like this?

![capture](https://cloud.githubusercontent.com/assets/7794777/5695325/322c9adc-99a5-11e4-8e0f-82ff1e818750.PNG)

**Comment by HaniAmmar** [comment]
Looks cool to me :)

Sorry for the late response, I've been busy.
________________________________

**Comment by di48l069** [comment]
hi there,

sorry to bother you but wondering if you can help me with something

Remember i said i want to use similar login style for my app, well i was wondering can you help by implementing the (save, reset and delete) as well as saving that infomation to appdata?

It will be really great if you can help if you have time,

**Comment by HaniAmmar** [comment]
Sure Man, you can skype me or email me. what do you want me to help you with? storage?

**Comment by di48l069** [comment]
Can you please provide me with your email :+1: so i can send you the info

**Comment by HaniAmmar** [comment]
shot at PlusFTP at outlook.com
